
const DefaultTheme = {
  background: '#f5f5f5',
  text: '#000000',
  sectionBackground: '#ffffff',
  divider: '#e0e0e0',
  iconBackground: '#eeeeee',
  switchThumb: '#ffffff',
  switchTrack: '#767577',
  container: '#f5f5f5',
  today: { 
    color:'cyan'
  },
  weekend: {
  color: 'orange'
  },
  label: '#c2c2c2',
  rate: '#c1c1c1',
  iconBackground: '#eeeeee',
  divider: '#e0e0e0',
  line: {
    color:'#e2e2e2'
  },
  searchContainer: '#eeeeee',
  sectionText: "#575767",
  textTask: {
    color: '#575767',
  },
  subtitle: {
    color:'#575767',
  },
  completedTask: {
    color: "#B9B9BE",
  },
  titleStyle: '#0E0E11',
  subtitleStyle: '#575767',
  lineStyle: '#D0D0D0',
  iconSun:'#ffcc00',
  icon: '#000',
  checkbox: '#FCFCFC',
  borderCheckbox: 'DADADA',
  checkmark: '#575767',
  thumbColor: '#fff',
  taskIncomplete: '#800000', 
  taskComplete: 'green', 
  transparent: 'transparent',
   favorite: '#0c86eb',
  unfavorite: '#0c86eb',
  checkbox: '#FCFCFC',
  borderColor: '#DADADA',
  strokeColor: '#575767',
  placeholder: '#888',
  addIcon: '#13518f',
  ativityIndicator: '#00ff00',
  headerPlaceholder: '#DADADA',
  taskModalPlaceholder: '#B0B0B0',
  today: '#00ccff',
  weekDay: '#575767',
  iconMenu: '#000000',
  bottomSheet: '#000000b3',
  bottomSheetMain: '#1c1c1e',
  searchContainerBottom: '#313036',
  cancelText: '#007AFF',
  borderBottom: '#1a1a1a',
  currency: '#efefef',
  addCurrencies: 'white',
  searchInput: 'white',
  noResults: 'white',
  header: 'black',
  edit: '#13518f',
  symbol: '#efefef',
  empty: 'white',
  calendar: '#007BFF',
  modalBackdrop: 'rgba(0, 0, 0, 0.5)',
  modal: '#141419',
  input: '#2c2c2e',
  button: '#2563EB',
  buttonBackground: 'transparent',
  section: '#DADADA',
  smallGroup: '#575767',
  red: 'red',
  modalOverlay: 'rgba(0,0,0,0.8)',
  black: 'black',
  floating: '#3F4EA0',
  floatingBorder: '#515CC6',
  combinedSection: '#333'
};

export default DefaultTheme;

